version: '3.8'

services:
  pgquerywatcher:
    image: golang:1.19-alpine
    env_file:
      - .env
    volumes:
      - ./watcher:/app:delegated
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh
    depends_on:
      - target_db
      - graylog
    working_dir: /app
    logging:
      driver: "gelf"
      options:
        gelf-address: "tcp://localhost:12201"
        tag: "first-logs"

  target_db:
    build:
      context: .
      dockerfile: postgres.Dockerfile
    environment:
      - TERM=xterm
      - POSTGRES_DB=target_db
      - POSTGRES_USER=target_user
      - POSTGRES_PASSWORD=target_pass
      - PAGER=less
    expose:
      - "5432"
    ports:
      - "5441:5432"
    volumes:
      - target_db:/var/lib/postgresql
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all

  mongodb:
    image: "mongo:5.0"
    volumes:
      - "mongodb_data:/data/db"
    restart: "on-failure"

  opensearch:
    image: "opensearchproject/opensearch:2.4.0"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "bootstrap.memory_lock=true"
      - "discovery.type=single-node"
      - "action.auto_create_index=false"
      - "plugins.security.ssl.http.enabled=false"
      - "plugins.security.disabled=true"
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
      - "os_data:/usr/share/opensearch/data"
    restart: "on-failure"

  graylog:
    image: graylog/graylog:5.0.2
    environment:
      GRAYLOG_NODE_ID_FILE: "/usr/share/graylog/data/config/node-id"
      GRAYLOG_HTTP_BIND_ADDRESS: "0.0.0.0:9000"
      GRAYLOG_HTTP_EXTERNAL_URI: "http://localhost:9000/"
      GRAYLOG_ELASTICSEARCH_HOSTS: "http://opensearch:9200"
      GRAYLOG_MONGODB_URI: "mongodb://mongodb:27017/graylog"
      # CHANGE ME (must be at least 16 characters)!
      GRAYLOG_PASSWORD_SECRET: "somepasswordpepper"
      # Password: admin
      GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
    entrypoint: "/usr/bin/tini -- wait-for-it opensearch:9200 --  /docker-entrypoint.sh"
    restart: "on-failure"
    depends_on:
      opensearch:
        condition: "service_started"
      mongodb:
        condition: "service_started"
    volumes:
      - "graylog_data:/usr/share/graylog/data/data"
      - "graylog_journal:/usr/share/graylog/data/journal"
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/udp"   # Syslog
      - "5140:5140/tcp"   # Syslog
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW TCP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      #- "10000:10000/tcp" # Custom TCP port
      #- "10000:10000/udp" # Custom UDP port
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config

volumes:
  target_db:
  mongodb_data:
  os_data:
  graylog_data:
  graylog_journal:

